ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS palette TEXT[] NOT NULL DEFAULT ARRAY['#FF8E9E', '#FFFFFF'];
ALTER TABLE products ADD COLUMN IF NOT EXISTS release_date DATE NOT NULL DEFAULT CURRENT_DATE;
