// =========================================
// tiny.fits — Product Data
// =========================================

const PRODUCTS = [
  {
    id: 1,
    name: "Colour-block hoodie",
    category: "tops",
    ages: "Ages 4–10",
    price: 28,
    oldPrice: null,
    badge: "new",
    emoji: "🧥",
    bg: "#EEEDFE",
    sizes: ["4y", "6y", "8y", "10y"],
  },
  {
    id: 2,
    name: "Floral wrap dress",
    category: "girls",
    ages: "Ages 3–8",
    price: 19,
    oldPrice: 27,
    badge: "sale",
    emoji: "👗",
    bg: "#FAECE7",
    sizes: ["3y", "5y", "7y"],
  },
  {
    id: 3,
    name: "Cargo joggers",
    category: "bottoms",
    ages: "Ages 6–14",
    price: 24,
    oldPrice: null,
    badge: "new",
    emoji: "👖",
    bg: "#E1F5EE",
    sizes: ["6y", "8y", "10y", "12y"],
  },
  {
    id: 4,
    name: "Velcro trainers",
    category: "footwear",
    ages: "Ages 1–5",
    price: 34,
    oldPrice: null,
    badge: null,
    emoji: "👟",
    bg: "#FBEAF0",
    sizes: ["EU 22", "EU 24", "EU 26"],
  },
  {
    id: 5,
    name: "Rainbow sock 5-pack",
    category: "accessories",
    ages: "Ages 2–8",
    price: 12,
    oldPrice: 15,
    badge: "sale",
    emoji: "🧦",
    bg: "#FAEEDA",
    sizes: ["S", "M"],
  },
  {
    id: 6,
    name: "Pull-on shorts",
    category: "bottoms",
    ages: "Ages 4–12",
    price: 16,
    oldPrice: null,
    badge: "new",
    emoji: "🩳",
    bg: "#EAF3DE",
    sizes: ["4y", "6y", "8y", "10y"],
  },
  {
    id: 7,
    name: "Knit mittens",
    category: "accessories",
    ages: "Ages 2–6",
    price: 10,
    oldPrice: null,
    badge: null,
    emoji: "🧤",
    bg: "#EEEDFE",
    sizes: ["One size"],
  },
  {
    id: 8,
    name: "Stripe scarf",
    category: "accessories",
    ages: "Ages 3–10",
    price: 14,
    oldPrice: null,
    badge: null,
    emoji: "🧣",
    bg: "#FAECE7",
    sizes: ["One size"],
  },
  {
    id: 9,
    name: "Logo cap",
    category: "accessories",
    ages: "Ages 4–12",
    price: 18,
    oldPrice: null,
    badge: null,
    emoji: "🧢",
    bg: "#E1F5EE",
    sizes: ["S", "M"],
  },
  {
    id: 10,
    name: "Swim bodysuit",
    category: "swimwear",
    ages: "Ages 0–18m",
    price: 22,
    oldPrice: null,
    badge: "new",
    emoji: "🩱",
    bg: "#FAEEDA",
    sizes: ["0m", "6m", "12m"],
  },
  {
    id: 11,
    name: "Denim dungarees",
    category: "girls",
    ages: "Ages 2–7",
    price: 32,
    oldPrice: 40,
    badge: "sale",
    emoji: "👘",
    bg: "#E6F1FB",
    sizes: ["2y", "3y", "5y", "7y"],
  },
  {
    id: 12,
    name: "Puffer jacket",
    category: "tops",
    ages: "Ages 4–12",
    price: 54,
    oldPrice: null,
    badge: "new",
    emoji: "🥼",
    bg: "#FCEBEB",
    sizes: ["4y", "6y", "8y", "10y", "12y"],
  },
];

export default PRODUCTS;
