import { create } from 'zustand'

const SAVED = localStorage.getItem('sk_lang') || 'en'

export const useLang = create(set => ({
  lang: SAVED,
  setLang(lang) {
    localStorage.setItem('sk_lang', lang)
    set({ lang })
  },
}))

export const T = {
  en: {
    girl: 'Girl',
    boy: 'Boy',
    toddlerGirl: 'Toddler Girl',
    toddlerBoy: 'Toddler Boy',
    baby: 'Baby',
    search: 'What are you looking for?',
    searchBtn: 'Search',
    signIn: 'Sign in',
    account: 'Account',
    bag: 'Bag',
    location: 'Delivery location',
    wishlist: 'Wishlist',
    locationTitle: 'Set delivery location',
    locationSub: 'Allow location access so we can show accurate delivery times and shipping costs.',
    allowBtn: 'Allow location',
    enterManual: 'Enter address manually',
    locationSaved: 'Location saved',
    sizes418: 'Sizes 4-18',
    sizes6m5t: 'Sizes 6M-5T',
    sizes024m: 'Sizes 0-24M',
    trendingNow: 'Trending Now',
    shoes: 'Shoes & Accessories',
    pajamas: 'Pajamas',
    shopByAge: 'Shop By Age',
    createAccount: 'Create Account',
    login: 'Login',
    specialOffers: 'Special Offers',
    seeAll: 'See all',
    home: 'Home',
    shop: 'Shop',
    checkout: 'Checkout',
    yourBag: 'Your bag',
    item: 'item',
    items: 'items',
    yourBagEmpty: 'Your bag is empty',
    continueShopping: 'Continue shopping',
    remove: 'Remove',
    size: 'Size',
    each: 'each',
    total: 'Total',
    updatingBag: 'Updating bag...',
    featured: 'Featured',
    newest: 'Newest',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    topRated: 'Top rated',
    az: 'A-Z',
    filters: 'Filters',
    close: 'Close',
    genderAge: 'Gender & Age',
    viewAllAges: 'View all ages',
    ageRange: 'Age range',
    allBoys: 'All boys',
    allGirls: 'All girls',
    toddlerSizes: 'Toddler sizes',
    allToddlerBoys: 'All toddler boys',
    allToddlerGirls: 'All toddler girls',
    babyGender: 'Baby gender',
    allBabies: 'All babies',
    babyBoys: 'Baby boys',
    babyGirls: 'Baby girls',
    sizeMonths: 'Size (months)',
    category: 'Category',
    all: 'All',
    maxPrice: 'Max price',
    availability: 'Availability',
    onSale: 'On sale',
    newIn: 'New in',
    clearAllFilters: 'Clear all filters',
    forSearch: 'for',
    warning: 'Warning',
    noProductsFound: 'No products found',
    tryAdjusting: 'Try adjusting your filters or search term.',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    productNotFound: 'Product not found.',
    loading: 'Loading...',
    pleaseSelectSize: 'Please select a size',
    reviews: 'reviews',
    addToBag: 'Add to bag',
    addedToBag: 'Added to bag!',
    freeDelivery50: 'Free delivery on orders over $50',
    freeReturns30: 'Free returns within 30 days',
    madeWithCotton: 'Made with GOTS certified cotton',
    youMightAlsoLike: 'You might also like',
    seeAllCategory: 'See all',
    shopping: 'Shopping',
    customerService: 'Customer Service',
    corporate: 'Corporate',
    policies: 'Policies',
    boys: 'Boys',
    girls: 'Girls',
    sale: 'Sale',
    sizeGuide: 'Size guide',
    returns: 'Returns',
    deliveryInfo: 'Delivery info',
    trackOrder: 'Track order',
    faqs: 'FAQs',
    ourStory: 'Our story',
    sustainability: 'Sustainability',
    press: 'Press',
    careers: 'Careers',
    contact: 'Contact',
    privacy: 'Privacy',
    terms: 'Terms',
    cookies: 'Cookies',
    footerTagline: 'Kidswear they love, at prices parents love.',
    allRightsReserved: 'All rights reserved.',
    mixTitle: 'Pick a top, pick a bottom, shop the whole look in one click!',
    loadingLooks: 'Loading looks...',
    previousTop: 'Previous top',
    nextTop: 'Next top',
    previousBottom: 'Previous bottom',
    nextBottom: 'Next bottom',
    addToBagUpper: 'ADD TO BAG',
    addedToBagUpper: 'ADDED TO BAG',
    color: 'Color',
    selectColor: 'Select color',
    sizeGuideShort: 'Size Guide',
    selectSize: 'Select a size',
    viewFullProductDetails: 'View Full Product Details',
    off: 'OFF',
    reviewItems: 'Review your items',
    readyToPlaceOrder: 'Ready to place your order',
    lines: 'lines',
    contactSection: 'Contact',
    shippingAddress: 'Shipping address',
    payment: 'Payment',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    firstName: 'First name',
    lastName: 'Last name',
    streetAddress: 'Street address',
    city: 'City',
    state: 'State',
    zipCode: 'ZIP code',
    cardNumber: 'Card number',
    cardExpiry: 'MM / YY',
    cardCvv: 'CVV',
    nameOnCard: 'Name on card',
    summary: 'Summary',
    orderTotals: 'Order totals',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    estimatedTax: 'Estimated tax',
    free: 'Free',
    placeOrder: 'Place order',
    updatingOrder: 'Updating order...',
    addMoreForFreeShipping: 'Add a little more to unlock free shipping at $50.',
    unlockedFreeShipping: 'You unlocked free shipping.',
    emptyCheckout: 'Add a few pieces before heading to checkout.',
    springSummer: 'Spring / Summer 2026',
    heroTitle: "Clothes they'll actually want to wear",
    heroSub: 'Comfy, durable, and ridiculously fun for ages 0-14. Free returns, always.',
    shopNewArrivals: 'Shop new arrivals',
    viewSale: 'View sale',
    freeReturns: 'Free returns',
    noQuestionsAsked: 'No questions asked',
    springPastels: 'Spring pastels\nare here',
    summerSale: 'Summer sale\nstarts now',
    shoesBuilt: 'Shoes built\nto be destroyed',
    shopNow: 'Shop now',
    shopFootwear: 'Shop footwear',
    newCollection: 'New collection',
    upTo40: 'Up to 40% off',
    footwearDrop: 'Footwear drop',
    newThisWeek: 'New in this week',
    trustDelivery: 'Free next-day delivery',
    trustDeliverySub: 'On orders over $50',
    trustReturns: 'Free returns',
    trustReturnsSub: 'No questions asked',
    trustSustainable: 'Sustainable materials',
    trustSustainableSub: 'GOTS certified cotton',
    trustTracked: 'Tracked shipping',
    trustTrackedSub: 'Know exactly where it is',
    gettingLocation: 'Getting location...',
    permissionDenied: 'Permission denied. Enter your address manually.',
    or: 'or',
    save: 'Save',
  },
  es: {
    girl: 'Niña',
    boy: 'Niño',
    toddlerGirl: 'Niña pequeña',
    toddlerBoy: 'Niño pequeño',
    baby: 'Bebé',
    search: '¿Qué estás buscando?',
    searchBtn: 'Buscar',
    signIn: 'Iniciar sesión',
    account: 'Cuenta',
    bag: 'Bolsa',
    location: 'Ubicación de entrega',
    wishlist: 'Favoritos',
    locationTitle: 'Establecer ubicación de entrega',
    locationSub: 'Permite el acceso a tu ubicación para mostrar tiempos de entrega y costos de envío precisos.',
    allowBtn: 'Permitir ubicación',
    enterManual: 'Ingresar dirección manualmente',
    locationSaved: 'Ubicación guardada',
    sizes418: 'Tallas 4-18',
    sizes6m5t: 'Tallas 6M-5T',
    sizes024m: 'Tallas 0-24M',
    trendingNow: 'Tendencias',
    shoes: 'Zapatos y accesorios',
    pajamas: 'Pijamas',
    shopByAge: 'Comprar por edad',
    createAccount: 'Crear cuenta',
    login: 'Iniciar sesión',
    specialOffers: 'Ofertas especiales',
    seeAll: 'Ver todo',
    home: 'Inicio',
    shop: 'Tienda',
    checkout: 'Pagar',
    yourBag: 'Tu bolsa',
    item: 'artículo',
    items: 'artículos',
    yourBagEmpty: 'Tu bolsa está vacía',
    continueShopping: 'Seguir comprando',
    remove: 'Quitar',
    size: 'Talla',
    each: 'cada uno',
    total: 'Total',
    updatingBag: 'Actualizando bolsa...',
    featured: 'Destacados',
    newest: 'Más nuevos',
    priceLowHigh: 'Precio: menor a mayor',
    priceHighLow: 'Precio: mayor a menor',
    topRated: 'Mejor valorados',
    az: 'A-Z',
    filters: 'Filtros',
    close: 'Cerrar',
    genderAge: 'Género y edad',
    viewAllAges: 'Ver todas las edades',
    ageRange: 'Rango de edad',
    allBoys: 'Todos los niños',
    allGirls: 'Todas las niñas',
    toddlerSizes: 'Tallas toddler',
    allToddlerBoys: 'Todos los niños toddler',
    allToddlerGirls: 'Todas las niñas toddler',
    babyGender: 'Género de bebé',
    allBabies: 'Todos los bebés',
    babyBoys: 'Bebés niño',
    babyGirls: 'Bebés niña',
    sizeMonths: 'Talla (meses)',
    category: 'Categoría',
    all: 'Todo',
    maxPrice: 'Precio máximo',
    availability: 'Disponibilidad',
    onSale: 'En oferta',
    newIn: 'Nuevo',
    clearAllFilters: 'Limpiar filtros',
    forSearch: 'para',
    warning: 'Aviso',
    noProductsFound: 'No se encontraron productos',
    tryAdjusting: 'Prueba ajustando tus filtros o búsqueda.',
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página',
    of: 'de',
    productNotFound: 'Producto no encontrado.',
    loading: 'Cargando...',
    pleaseSelectSize: 'Selecciona una talla',
    reviews: 'reseñas',
    addToBag: 'Agregar a la bolsa',
    addedToBag: 'Agregado a la bolsa',
    freeDelivery50: 'Entrega gratis en pedidos mayores a $50',
    freeReturns30: 'Devoluciones gratis dentro de 30 días',
    madeWithCotton: 'Hecho con algodón certificado GOTS',
    youMightAlsoLike: 'También te puede gustar',
    seeAllCategory: 'Ver todo',
    shopping: 'Compras',
    customerService: 'Atención al cliente',
    corporate: 'Corporativo',
    policies: 'Políticas',
    boys: 'Niños',
    girls: 'Niñas',
    sale: 'Oferta',
    sizeGuide: 'Guía de tallas',
    returns: 'Devoluciones',
    deliveryInfo: 'Información de entrega',
    trackOrder: 'Rastrear pedido',
    faqs: 'Preguntas frecuentes',
    ourStory: 'Nuestra historia',
    sustainability: 'Sustentabilidad',
    press: 'Prensa',
    careers: 'Carreras',
    contact: 'Contacto',
    privacy: 'Privacidad',
    terms: 'Términos',
    cookies: 'Cookies',
    footerTagline: 'Moda infantil que aman, a precios que encantan.',
    allRightsReserved: 'Todos los derechos reservados.',
    mixTitle: 'Elige una parte de arriba, una de abajo y compra el look completo en un clic.',
    loadingLooks: 'Cargando looks...',
    previousTop: 'Parte de arriba anterior',
    nextTop: 'Siguiente parte de arriba',
    previousBottom: 'Parte de abajo anterior',
    nextBottom: 'Siguiente parte de abajo',
    addToBagUpper: 'AGREGAR A LA BOLSA',
    addedToBagUpper: 'AGREGADO A LA BOLSA',
    color: 'Color',
    selectColor: 'Selecciona color',
    sizeGuideShort: 'Guía de tallas',
    selectSize: 'Selecciona una talla',
    viewFullProductDetails: 'Ver detalles completos',
    off: 'DE DESCUENTO',
    reviewItems: 'Revisa tus artículos',
    readyToPlaceOrder: 'Listo para hacer tu pedido',
    lines: 'líneas',
    contactSection: 'Contacto',
    shippingAddress: 'Dirección de envío',
    payment: 'Pago',
    emailAddress: 'Correo electrónico',
    phoneNumber: 'Número de teléfono',
    firstName: 'Nombre',
    lastName: 'Apellido',
    streetAddress: 'Dirección',
    city: 'Ciudad',
    state: 'Estado',
    zipCode: 'Código postal',
    cardNumber: 'Número de tarjeta',
    cardExpiry: 'MM / AA',
    cardCvv: 'CVV',
    nameOnCard: 'Nombre en la tarjeta',
    summary: 'Resumen',
    orderTotals: 'Totales del pedido',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    estimatedTax: 'Impuesto estimado',
    free: 'Gratis',
    placeOrder: 'Realizar pedido',
    updatingOrder: 'Actualizando pedido...',
    addMoreForFreeShipping: 'Agrega un poco más para obtener envío gratis a partir de $50.',
    unlockedFreeShipping: 'Ya desbloqueaste el envío gratis.',
    emptyCheckout: 'Agrega algunas prendas antes de pasar al pago.',
    springSummer: 'Primavera / Verano 2026',
    heroTitle: 'Ropa que sí van a querer usar',
    heroSub: 'Cómoda, duradera y divertidísima para edades de 0 a 14. Devoluciones gratis, siempre.',
    shopNewArrivals: 'Comprar novedades',
    viewSale: 'Ver ofertas',
    freeReturns: 'Devoluciones gratis',
    noQuestionsAsked: 'Sin preguntas',
    springPastels: 'Los tonos pastel\nde primavera ya llegaron',
    summerSale: 'La oferta de verano\nya comenzó',
    shoesBuilt: 'Zapatos hechos\npara sobrevivirlo todo',
    shopNow: 'Comprar ahora',
    shopFootwear: 'Comprar calzado',
    newCollection: 'Nueva colección',
    upTo40: 'Hasta 40% de descuento',
    footwearDrop: 'Nuevo calzado',
    newThisWeek: 'Novedades de la semana',
    trustDelivery: 'Entrega al día siguiente',
    trustDeliverySub: 'En pedidos mayores a $50',
    trustReturns: 'Devoluciones gratis',
    trustReturnsSub: 'Sin preguntas',
    trustSustainable: 'Materiales sustentables',
    trustSustainableSub: 'Algodón certificado GOTS',
    trustTracked: 'Envío rastreable',
    trustTrackedSub: 'Sabrás dónde está siempre',
    gettingLocation: 'Obteniendo ubicación...',
    permissionDenied: 'Permiso denegado. Ingresa tu dirección manualmente.',
    or: 'o',
    save: 'Guardar',
  },
}

export function t(lang, key) {
  return T[lang]?.[key] ?? T.en[key] ?? key
}
